### ISSUE TITLE
Add support for DOT

### ISSUE THREAD

**Issue by TomHsiung** [rgd87/NugPlateAuras#3]
Hello, pal

I am a warlock and shadow priest. I don't know how to display the DOT on the nameplate with this lovely add-on. Would you mind telling me that? Thank you

PS: Burning Crusade Classic

Tom

**Comment by d87** [comment]
This addon isn't aimed at dots. For dots you better use either any full-featured nameplate replacement addon (Threat Plates, KuiNameplates, Plater) or NugRunning also adds nameplate bars for dots. Other addons that just add debuffs to classic nameplates exist too i'm sure
But if you must, the key to what's shown or not is the Libs/LibAuraTypes/LibAuraTypes.lua file. if you add there your dots' spell IDs with high priority they'll be shown

**Comment by TomHsiung** [comment]
Thank you, pal
